CREATE PROCEDURE `gbfg_Grid_InsertUpdate`(
		IN _ID INT(11),
		IN _slug VARCHAR(100),
		IN _GridData LONGTEXT,
		IN _Class VARCHAR(100),
		IN _MCDisabled VARCHAR(10),
		IN _Character1 VARCHAR(100),
		IN _Character1Disabled VARCHAR(10),
		IN _Character2 VARCHAR(100),
		IN _Character2Disabled VARCHAR(10),
		IN _Character3 VARCHAR(100),
		IN _Character3Disabled VARCHAR(10),
		IN _Character4 VARCHAR(100),
		IN _Character4Disabled VARCHAR(10),
		IN _Character5 VARCHAR(100),
		IN _Character5Disabled VARCHAR(10),
		IN _Skill1 VARCHAR(100),
		IN _Skill2 VARCHAR(100),
		IN _Skill3 VARCHAR(100),
		IN _ClassItemTypeID INT(11),
		IN _ClassItem1 VARCHAR(100),
		IN _ClassItem2 VARCHAR(100),
		IN _ClassItem3 VARCHAR(100),
		IN _ClassItem4 VARCHAR(100),
		IN _ClassItem5 VARCHAR(100),
		IN _ClassItem6 VARCHAR(100),
		IN _Summon1 VARCHAR(100),
		IN _Summon2 VARCHAR(100),
		IN _Summon3 VARCHAR(100),
		IN _Summon4 VARCHAR(100),
		IN _Summon5 VARCHAR(100),
		IN _Summon6 VARCHAR(100),
		IN _SummonMain VARCHAR(100),
		IN _SummonFriend VARCHAR(100),
		IN _QuickSummon VARCHAR(45),
		IN _Weapon1 VARCHAR(100),
		IN _Weapon2 VARCHAR(100),
		IN _Weapon3 VARCHAR(100),
		IN _Weapon4 VARCHAR(100),
		IN _Weapon5 VARCHAR(100),
		IN _Weapon6 VARCHAR(100),
		IN _Weapon7 VARCHAR(100),
		IN _Weapon8 VARCHAR(100),
		IN _Weapon9 VARCHAR(100),
		IN _Weapon10 VARCHAR(100),
		IN _Weapon11 VARCHAR(100),
		IN _Weapon12 VARCHAR(100),
		IN _Weapon13 VARCHAR(100),
		IN _ShowExtraSlots BIT(1),
		IN _WeaponsOnly BIT(1),
		IN _ShowBooks BIT(1),
		IN _Book1 VARCHAR(100),
		IN _Book2 VARCHAR(100),
		IN _Book3 VARCHAR(100)
)
BEGIN
	SET _slug = gbfg_CleanSlug(_slug);

	IF EXISTS(SELECT * FROM gbfg_Grids WHERE ID = _ID) THEN
		UPDATE `gbfguide_maindata`.`gbfg_Grids`
		SET
		`ID` = _ID,
		`slug` = _slug,
		`GridData` = _GridData,
		`Class` = _Class,
		`Character1` = _Character1,
		`Character2` = _Character2,
		`Character3` = _Character3,
		`Character4` = _Character4,
		`Character5` = _Character5,
		`MCDisabled` = _MCDisabled,
		`Character1Disabled` = _Character1Disabled,
		`Character2Disabled` = _Character2Disabled,
		`Character3Disabled` = _Character3Disabled,
		`Character4Disabled` = _Character4Disabled,
		`Character5Disabled` = _Character5Disabled,
		`Skill1` = _Skill1,
		`Skill2` = _Skill2,
		`Skill3` = _Skill3,
		`Summon1` = _Summon1,
		`Summon2` = _Summon2,
		`Summon3` = _Summon3,
		`Summon4` = _Summon4,
		`Summon5` = _Summon5,
		`Summon6` = _Summon6,
		`SummonMain` = _SummonMain,
		`SummonFriend` = _SummonFriend,
		`QuickSummon` = _QuickSummon,
		`Weapon1` = _Weapon1,
		`Weapon2` = _Weapon2,
		`Weapon3` = _Weapon3,
		`Weapon4` = _Weapon4,
		`Weapon5` = _Weapon5,
		`Weapon6` = _Weapon6,
		`Weapon7` = _Weapon7,
		`Weapon8` = _Weapon8,
		`Weapon9` = _Weapon9,
		`Weapon10` = _Weapon10,
		`Weapon11` = _Weapon11,
		`Weapon12` = _Weapon12,
		`Weapon13` = _Weapon13,
		`ShowExtraSlots` = _ShowExtraSlots,
		`ClassItemTypeID` = _ClassItemTypeID,
		`ClassItem1` = _ClassItem1,
		`ClassItem2` = _ClassItem2,
		`ClassItem3` = _ClassItem3,
		`ClassItem4` = _ClassItem4,
		`ClassItem5` = _ClassItem5,
		`ClassItem6` = _ClassItem6,
		`WeaponsOnly` = _WeaponsOnly,
		`ShowBooks` = _ShowBooks,
		`Book1` = _Book1,
		`Book2` = _Book2,
		`Book3` = _Book3
		WHERE `ID` = _ID;
	ELSE
		INSERT INTO `gbfguide_maindata`.`gbfg_Grids`(
			`ID`,
			`slug`,
			`GridData`,
			`Class`,
			`Character1`,
			`Character2`,
			`Character3`,
			`Character4`,
			`Character5`,
			`MCDisabled`,
			`Character1Disabled`,
			`Character2Disabled`,
			`Character3Disabled`,
			`Character4Disabled`,
			`Character5Disabled`,
			`Skill1`,
			`Skill2`,
			`Skill3`,
			`Summon1`,
			`Summon2`,
			`Summon3`,
			`Summon4`,
			`Summon5`,
			`Summon6`,
			`SummonMain`,
			`SummonFriend`,
			`QuickSummon`,
			`Weapon1`,
			`Weapon2`,
			`Weapon3`,
			`Weapon4`,
			`Weapon5`,
			`Weapon6`,
			`Weapon7`,
			`Weapon8`,
			`Weapon9`,
			`Weapon10`,
			`Weapon11`,
			`Weapon12`,
			`Weapon13`,
			`ShowExtraSlots`,
			`ClassItemTypeID`,
			`ClassItem1`,
			`ClassItem2`,
			`ClassItem3`,
			`ClassItem4`,
			`ClassItem5`,
			`ClassItem6`,
			`WeaponsOnly`,
			`ShowBooks`,
			`Book1`,
			`Book2`,
			`Book3`
		)
		VALUES (
			_ID,
			_slug,
			_GridData,
			_Class,
			_Character1,
			_Character2,
			_Character3,
			_Character4,
			_Character5,
			_MCDisabled,
			_Character1Disabled,
			_Character2Disabled,
			_Character3Disabled,
			_Character4Disabled,
			_Character5Disabled,
			_Skill1,
			_Skill2,
			_Skill3,
			_Summon1,
			_Summon2,
			_Summon3,
			_Summon4,
			_Summon5,
			_Summon6,
			_SummonMain,
			_SummonFriend,
			_QuickSummon,
			_Weapon1,
			_Weapon2,
			_Weapon3,
			_Weapon4,
			_Weapon5,
			_Weapon6,
			_Weapon7,
			_Weapon8,
			_Weapon9,
			_Weapon10,
			_Weapon11,
			_Weapon12,
			_Weapon13,
			_ShowExtraSlots,
			_ClassItemTypeID,
			_ClassItem1,
			_ClassItem2,
			_ClassItem3,
			_ClassItem4,
			_ClassItem5,
			_ClassItem6,
			_WeaponsOnly,
			_ShowBooks,
			_Book1,
			_Book2,
			_Book3
		);
	END IF;
END